

# This file was *autogenerated* from the file code.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_10 = Integer(10); _sage_const_0 = Integer(0); _sage_const_3 = Integer(3); _sage_const_5 = Integer(5); _sage_const_1p5 = RealNumber('1.5'); _sage_const_0p35 = RealNumber('0.35'); _sage_const_0p5 = RealNumber('0.5'); _sage_const_300 = Integer(300)
for M in range(_sage_const_1 ,_sage_const_10 ): 
    for i,d in enumerate(DirichletGroup(M)): 
        o = circle(center=(_sage_const_0 ,_sage_const_0 ),radius =sqrt(M),color="grey") 
        rs = [Color(r) for r in rainbow(M)] 
        for r in range(M): 
            z = CC.zeta(M)**r 
            po = [CC(_sage_const_0 )] 
            zi = z 
            for n in range(_sage_const_1 ,M): 
                po.append(po[-_sage_const_1 ] + d(n)*zi) 
                zi *= z 
                o += line([CC(_sage_const_0 ),po[-_sage_const_1 ]],color=rs[r].darker((M - _sage_const_1  - n)*_sage_const_3 /(_sage_const_5 *M)), thickness=_sage_const_1p5 , alpha=_sage_const_0p35 ) 
            print(r,po[-_sage_const_1 ]) 
            o += point(po[-_sage_const_1 ], zorder=_sage_const_10 , color=rs[r], alpha=_sage_const_0p5 ) 
 
        o.save("%s-%s.png"%(M,d.conrey_number()),dpi=_sage_const_300 ,axes=False,fig_tight=False, figsize=[_sage_const_5 ,_sage_const_5 ]) 

